#!/usr/bin/env bash
# Typecheck against the globally installed Pi packages, wherever npm put them.
#
# This repo has no node_modules: Pi's loader supplies its packages at runtime and Node 24 strips
# types for the tests. Only tsc needs to be told where Pi's type declarations live, and that path
# differs per machine, so it is resolved here into tsconfig.tsc.json (gitignored) which extends
# the checked-in tsconfig.json.
#
# Override the location with PI_DIR=/path/to/@earendil-works/pi-coding-agent
set -euo pipefail
cd "$(dirname "$0")/.."

PI_DIR="${PI_DIR:-$(npm root -g)/@earendil-works/pi-coding-agent}"
if [ ! -d "$PI_DIR/dist" ]; then
	echo "Pi types not found at: $PI_DIR" >&2
	echo "Install Pi with: npm install -g --ignore-scripts @earendil-works/pi-coding-agent" >&2
	echo "Or point PI_DIR at an existing installation." >&2
	exit 1
fi

node --input-type=module -e '
import { writeFileSync } from "node:fs";
const pi = process.argv[1];
const nm = `${pi}/node_modules`;
const config = {
	"//": "Generated by scripts/typecheck.sh. Do not edit; edit tsconfig.json instead.",
	extends: "./tsconfig.json",
	compilerOptions: {
		typeRoots: [`${nm}/@types`],
		paths: {
			"@earendil-works/pi-coding-agent": [`${pi}/dist/index.d.ts`],
			"@earendil-works/pi-ai": [`${nm}/@earendil-works/pi-ai/dist/index.d.ts`],
			"@earendil-works/pi-tui": [`${nm}/@earendil-works/pi-tui/dist/index.d.ts`],
			"@earendil-works/pi-agent-core": [`${nm}/@earendil-works/pi-agent-core/dist/index.d.ts`],
			typebox: [`${nm}/typebox/build/index.d.mts`],
		},
	},
};
writeFileSync("tsconfig.tsc.json", `${JSON.stringify(config, null, "\t")}\n`);
' "$PI_DIR"

exec npx -y -p typescript tsc --noEmit -p tsconfig.tsc.json
